config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    post 'upvote'
    post 'downvote'
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :author, :presence => true
  validates :content, :presence => true 
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :artist_name, :presence => true
  validates :content, :presence => true

  scope :alphaAsc, -> { order(artist_name: :asc)}
  scope :alphaDesc, -> { order(artist_name: :desc)}
  scope :creationNew, -> { order(created_at: :desc)}
  scope :creationOld, -> { order(created_at: :asc)}
  scope :mostComments, -> {(
    select("posts.id, posts.artist_name, count(comments.id) as comments_count")
      .joins(:comments)
      .group("posts.id")
      .order("comments_count DESC")
      .limit(5)
    )}
  scope :leastComments, -> {(
    select("posts.id, posts.artist_name, count(comments.id) as comments_count")
      .joins(:comments)
      .group("posts.id")
      .order("comments_count ASC")
      .limit(5)
    )}
  scope :highestRating, -> { order(rating: :desc).limit(5)}

  def upvote
    self.rating += 1
  end

  def downvote
    self.rating -= 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.rating = 0
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def upvote
    @post = Post.find(params[:post_id])
    current_rating = @post.upvote
    @post.update(rating: current_rating)
    redirect_to (request.env['HTTP_REFERER'])
  end

  def downvote
    @post = Post.find(params[:post_id])
    current_rating = @post.downvote
    @post.update(rating: current_rating)
    redirect_to (request.env['HTTP_REFERER'])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:artist_name, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [ @post, @comment ] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit this Comment</h1>

<%= render "form" %>

app/views/comments/new.html.erb
<h1>Add a Comment</h1>

<%= render "form" %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opsynthpop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit "<%= @post.artist_name %>" </h1>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <h1>OperaticSynthPop</h1>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/PWmfNeLs7fA" frameborder="0" allowfullscreen></iframe>
  <h4>We know good music......now you will too</h4>

</div>

<div class="row">
  <div class="col-md-8">
    <h3>All Posts</h3>
    <ul>
    
      <% @posts.creationNew.each do |post| %>
        <li><%= link_to post.artist_name, post_path(post) %></li>
      <% end %>
    </ul>
    <%= link_to "Create New Post", new_post_path %>
  </div>

  <div class="col-md-4">
    <h3>Most Popular Posts</h3>
    <ul>
      <% @posts.highestRating.each do |post| %>
        <li><%= link_to post.artist_name, post_path(post) %></li>
      <% end %>
    </ul>

    <h3>Most Engaging Posts</h3>
    <ul>
      <% @posts.mostComments.each do |post| %>
        <li><%= link_to post.artist_name, post_path(post) %></li>
      <% end %>
    </ul>

    <h3>Start a Conversation</h3>
    <p>these posts don't have any comments yet</p>
    <ul>
      <% @posts.leastComments.each do |post| %>
        <li><%= link_to post.artist_name, post_path(post) %></li>
      <% end %>
    </ul>


  </div>
</div>

app/views/posts/new.html.erb
<h1>Create a Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.artist_name %></h1>
<p>Current Rating: <strong><%= @post.rating %></strong></p>
<%= button_to '^', post_upvote_path(@post) %>
<%= button_to 'v', post_downvote_path(@post) %>


<p><%= @post.content %></p>

<% if @post.comments.any? %>
  <% @post.comments.each do |comment| %>
    <p><%= comment.author %> | Created At: <%= comment.created_at %> | Updated At: <%= comment.updated_at %></p>
    <p><%= comment.content %></p>
    <%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %> | <%= link_to "Delete Comment", post_comment_path(@post, comment), :data => {
      :confirm => "You sure you want to delete this comment?",
      :method => "delete" } %> |
  <% end %>
<% else %>
  <p>No comments yet! Be the first one to comment.</p>
<% end %>
<%= link_to "Add a Comment", new_post_comment_path(@post) %>
<br>
<hr>
<%= link_to "Edit this Post", edit_post_path(@post) %> | <%= link_to "Delete this Post", post_path(@post), :data => {
      :confirm => "You sure you want to delete this post?",
      :method => "delete" } %>
<br>
<%= link_to "All Posts", posts_path %>